name: PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py
    - name: Upload .app
      uses: actions/upload-artifact@v2
      with:
        name: SceneDetector.app
        path: dist/main.app
            
    
        
